export const SUCESSFULL_OPERATION_NUMBER = 0;
export const FAILED_OPERATION_NUMBER = 1;

export const USER_STATUS_INACTIVE = 1;
export const USER_STATUS_ACTIVE = 2;
export const USER_STATUS_DELETED = 3;
export const USER_STATUS_REJECTED = 4;

export const USER_STATUS = {
  INACTIVE: USER_STATUS_INACTIVE,
  ACTIVE: USER_STATUS_ACTIVE,
  DELETED: USER_STATUS_DELETED,
  REJECTED: USER_STATUS_REJECTED,
};

export const PRODUCT_STATUS_INACTIVE = 0;
export const PRODUCT_STATUS_ACTIVE = 1;
export const PRODUCT_STATUS_DELETED = 2;

export const PRODUCT_STATUS = {
  INACTIVE: PRODUCT_STATUS_INACTIVE,
  ACTIVE: PRODUCT_STATUS_ACTIVE,
  DELETED: PRODUCT_STATUS_DELETED,
};